### ISSUE TITLE
The location of the training and testing dataset

### ISSUE THREAD

**Issue by YurongChen1998** [Zeqiang-Lai/MAN#1]
Thanks for your code. I would like to ask where is the location of training and testing dataset?

**Comment by Zeqiang-Lai** [comment]
Thanks for the attention, they are hosted in https://github.com/bit-isp/HSIR （Benchmark section). 

Put it here for convenience. 
[Datasets](https://pan.baidu.com/s/1BkNYhb9CBtXnKsQjNwYFyg#list/path=%2Fsharelink486539321-639622829333524%2FDataset&parentPath=%2Fsharelink486539321-639622829333524)

Baidu drive code for accessing is `HSIR`. For the requested dataset, please refer to this location `Dataset/Denoise/`

Ping me if there is any issue for the datasets.
