### ISSUE TITLE
Number of training sets

### ISSUE THREAD

**Issue by SuperQiang-boop** [Zeqiang-Lai/MAN#2]
Dear author，
Thanks for the code.How many 64x64 patch blocks are typically generated in your training set?

**Comment by Zeqiang-Lai** [comment]
It is roughly 50k. Our training dataset is publicly available at [Baidu Drive](https://pan.baidu.com/s/1BkNYhb9CBtXnKsQjNwYFyg?_at_=1680705745413#list/path=%2Fsharelink486539321-639622829333524%2FDataset%2FDenoise&parentPath=%2Fsharelink486539321-639622829333524), 提取码 HSIR

**Comment by SuperQiang-boop** [comment]
Thank you very much!

**Comment by SuperQiang-boop** [comment]
您好！
  打扰了，关于ICVL测试我还不是特别清楚
  ①如果测试高斯噪声σ=30的情况下，就是把测试数据裁剪为512x512x31patch之后再添加模拟噪声放入预训练好的网络吗？
  ②关于裁剪512x512x31的patch块，每个原图像只裁剪一个patch就可以了吗？
感谢您的回复！

**Comment by Zeqiang-Lai** [comment]
是的，每个图像只裁剪一个区域。因为ICVL数据集很多 object的图有效区域只有中间下方的一小块，我们裁剪的时候主要是保证那部分可以包括进来。

这里有我们处理好的测试集，你可以直接下载使用

提取码 HSIR
[测试集](https://pan.baidu.com/s/1BkNYhb9CBtXnKsQjNwYFyg#list/path=%2Fsharelink486539321-639622829333524%2FDataset%2FDenoise%2FICVL_Test&parentPath=%2Fsharelink486539321-639622829333524)

**Comment by SuperQiang-boop** [comment]
请问这是裁剪好的干净图像吗？

**Comment by Zeqiang-Lai** [comment]
每个mat包含干净图像和带噪输入

**Comment by SuperQiang-boop** [comment]
感谢！

**Comment by SuperQiang-boop** [comment]
请问你用的是多大的显存跑得512x512x31的测试集呀？

**Comment by Zeqiang-Lai** [comment]
MAN-L要13个G，M和S应该在12个G以下

**Comment by SuperQiang-boop** [comment]
请问可以分享一下真实噪声数据集Urban吗？我链接一直进不去，感谢回复！

**Comment by Zeqiang-Lai** [comment]
> It is roughly 50k. Our training dataset is publicly available at [Baidu Drive](https://pan.baidu.com/s/1BkNYhb9CBtXnKsQjNwYFyg?_at_=1680705745413#list/path=%2Fsharelink486539321-639622829333524%2FDataset%2FDenoise&parentPath=%2Fsharelink486539321-639622829333524), 提取码 HSIR

还是这

**Comment by SuperQiang-boop** [comment]
谢谢
