### ISSUE TITLE
您好，按照您给的训练命令，出现错误“train.py: error: unrecognized arguments: -s schedule.gaussian”，请问如何解决？hsir中没有-s的指令，您在训练中是如何使用的？

### ISSUE THREAD

**Issue by lin1yu** [Zeqiang-Lai/MAN#3]
![image](https://user-images.githubusercontent.com/130441225/232312159-3e89bf40-b699-4735-a05e-9e3d2bd1b13d.png)

**Comment by Zeqiang-Lai** [comment]
最新版的hsir应该是有的，

https://github.com/bit-isp/HSIR/blob/9988a26aeb841cbf12273fcbd2318baafed74a7b/hsirun/train.py#L20

这边建议您通过以下指令更新一下hsir（pypi上的可能不是最新的）
```bash
pip uninstall hsir
pip install git+https://github.com/bit-isp/HSIR.git
```

**Comment by lin1yu** [comment]
您好，按您给的命令输入后，出现了这个问题，请问是什么原因



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zeqiang ***@***.***&gt;; 
发送时间: 2023年4月16日(星期天) 晚上8:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Zeqiang-Lai/MAN] 您好，按照您给的训练命令，出现错误“train.py: error: unrecognized arguments: -s schedule.gaussian”，请问如何解决？hsir中没有-s的指令，您在训练中是如何使用的？ (Issue #3)





 
最新版的hsir应该是有的，
 https://github.com/bit-isp/HSIR/blob/9988a26aeb841cbf12273fcbd2318baafed74a7b/hsirun/train.py#L20
 
这边建议您通过以下指令更新一下hsir（pypi上的可能不是最新的）
 pip uninstall hsir pip install git+https://github.com/bit-isp/HSIR.git

**Comment by Zeqiang-Lai** [comment]
请问是什么问题呢？你的回复里没有包含问题

**Comment by lin1yu** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zeqiang ***@***.***&gt;; 
发送时间: 2023年4月16日(星期天) 晚上9:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Zeqiang-Lai/MAN] 您好，按照您给的训练命令，出现错误“train.py: error: unrecognized arguments: -s schedule.gaussian”，请问如何解决？hsir中没有-s的指令，您在训练中是如何使用的？ (Issue #3)





 
请问是什么问题呢？你的回复里没有包含问题

**Comment by lin1yu** [comment]
您好，问题图片在附件，麻烦您帮忙看一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Zeqiang-Lai/MAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月16日(星期天) 晚上9:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Zeqiang-Lai/MAN] 您好，按照您给的训练命令，出现错误“train.py: error: unrecognized arguments: -s schedule.gaussian”，请问如何解决？hsir中没有-s的指令，您在训练中是如何使用的？ (Issue #3)





 
请问是什么问题呢？你的回复里没有包含问题

**Comment by Zeqiang-Lai** [comment]
还是没有，你可以在github上直接回

**Comment by lin1yu** [comment]
我这边重启了一下服务器，按照您给命令，新版的hsir安装成功了，非常感谢



---原始邮件---
发件人: "Zeqiang ***@***.***&gt;
发送时间: 2023年4月16日(周日) 晚上9:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Zeqiang-Lai/MAN] 您好，按照您给的训练命令，出现错误“train.py: error: unrecognized arguments: -s schedule.gaussian”，请问如何解决？hsir中没有-s的指令，您在训练中是如何使用的？ (Issue #3)




 
还是没有，你可以在github上直接回

**Comment by Zeqiang-Lai** [comment]
好的不客气

**Comment by lin1yu** [comment]
![image](https://user-images.githubusercontent.com/130441225/232360703-136bca0c-a400-44e1-9526-16f94ca9edf2.png)
您好，在输入训练命令之后出现上面的问题，请问是什么原因

**Comment by Zeqiang-Lai** [comment]
```
python -m hsirun.train -a mans.man -s schedule.gaussian
```
这个命令里的 schedule 是 MAN 仓库下的 schedue.py 文件，gaussian是里面的一个schedule。所以你得在schedule.py所在文件夹运行指令。

**Comment by lin1yu** [comment]
谢谢您，是我的疏忽，切换窗口后当前文件位置变了

**Comment by lin1yu** [comment]
![image](https://user-images.githubusercontent.com/130441225/232686813-16805385-8ba1-40e2-ab3d-4a5909049d51.png)
您好，在训练1个epoch验证的时候出现了上图的keyerror的错误，请问这是什么原因？

**Comment by Zeqiang-Lai** [comment]
测试集的格式不对，

你可以从这里下载我们处理好的[测试集](https://pan.baidu.com/s/1BkNYhb9CBtXnKsQjNwYFyg#list/path=%2Fsharelink486539321-639622829333524%2FDataset%2FDenoise%2FICVL_Test&parentPath=%2Fsharelink486539321-639622829333524)

**Comment by lin1yu** [comment]
您好，测试集的百度网盘提取码提供一下

**Comment by Zeqiang-Lai** [comment]
提取码为 HSIR

**Comment by lin1yu** [comment]
数据集正在下载，非常感谢您的帮助

**Comment by lin1yu** [comment]
您好，请问为什么您的MAN方法这篇论文里展示的SAM结果和别人论文展示SAM结果的差距那么大呢？

**Comment by Zeqiang-Lai** [comment]
> 您好，请问为什么您的MAN方法这篇论文里展示的SAM结果和别人论文展示SAM结果的差距那么大呢？

应该是计算方法不同，你可以对比一下计算SAM的code

**Comment by lin1yu** [comment]
你们计算方法好像没区别，这是你的：
![image](https://github.com/Zeqiang-Lai/MAN/assets/130441225/7fbc94e7-99ed-4272-8871-9ad108067755)
这是别人的：
![image](https://github.com/Zeqiang-Lai/MAN/assets/130441225/2eae55c1-491f-4553-a13a-90d7f2e53203)

**Comment by Zeqiang-Lai** [comment]
那应该不会有问题呀。请问具体是差多大呢，跟哪篇论文对比？

**Comment by lin1yu** [comment]
“Spectral Enhanced Rectangle Transformer for Hyperspectral Image Denoising”这篇论文里面的SAM值是您论文里的大的



---原始邮件---
发件人: "Zeqiang ***@***.***&gt;
发送时间: 2023年6月30日(周五) 晚上11:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Zeqiang-Lai/MAN] 您好，按照您给的训练命令，出现错误“train.py: error: unrecognized arguments: -s schedule.gaussian”，请问如何解决？hsir中没有-s的指令，您在训练中是如何使用的？ (Issue #3)




 
那应该不会有问题呀。请问具体是差多大呢，跟哪篇论文对比？

**Comment by Zeqiang-Lai** [comment]
SERT 的SAM计算代码实际上可能是这个，它乘了180/pi

https://github.com/MyuLi/SERT/blob/9cc1b5038f65ab25663f768449d8b0ac92f09ab7/hsi_setup.py#L502

**Comment by lin1yu** [comment]
我大概知道了，非常感谢您



---原始邮件---
发件人: "Zeqiang ***@***.***&gt;
发送时间: 2023年7月1日(周六) 凌晨0:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Zeqiang-Lai/MAN] 您好，按照您给的训练命令，出现错误“train.py: error: unrecognized arguments: -s schedule.gaussian”，请问如何解决？hsir中没有-s的指令，您在训练中是如何使用的？ (Issue #3)




 
SERT 的SAM计算代码实际上可能是这个，它乘了180/pi
 
https://github.com/MyuLi/SERT/blob/9cc1b5038f65ab25663f768449d8b0ac92f09ab7/hsi_setup.py#L502

**Comment by lin1yu** [comment]
您好，请问您采用的ICVL测试集中每种类型的复杂噪声是如何设置的？

**Comment by Zeqiang-Lai** [comment]
这部分完全来自QRNN3D，可以参考 QRNN3D 的代码和论文。

**Comment by lin1yu** [comment]
好的，谢谢
